$(document).ready ->
  $(window).scroll ->
    if $(this).scrollTop() > 100
      $('.scrollup').fadeIn()
    else
      $('.scrollup').fadeOut()
    return
  $('.scrollup').click ->
    $('html, body').animate { scrollTop: 0 }, 600
    false
  return

# ---
# generated by js2coffee 2.2.0
